#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export QT_PLUGIN_PATH="${HERE}/usr/lib/qt/plugins"
export QML2_IMPORT_PATH="${HERE}/usr/lib/qt/qml"

exec "${HERE}/usr/bin/glance" "$@"
